services:
  # Flask应用服务 - 生产环境配置
  household-data-app:
    # 使用预构建的应用镜像
    image: ${REGISTRY_URL:-}household-data-system-app:${VERSION:-latest}

    container_name: household-data-system-prod
    restart: unless-stopped
    network_mode: "host"
    
    environment:
      # Flask配置 - 生产环境
      - FLASK_ENV=production
      - FLASK_DEBUG=0
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
      
      # 数据库配置 - 内部数据库
      - DB_DRIVER=${DB_DRIVER:-ODBC Driver 18 for SQL Server}
      - DB_SERVER=${DB_SERVER:-localhost}
      - DB_DATABASE=${DB_DATABASE:-hhgzhdc}
      - DB_UID=${DB_UID:-sa}
      - DB_PWD=${DB_PWD}
      - DB_ENCRYPT=${DB_ENCRYPT:-yes}
      - DB_TRUST_CERT=${DB_TRUST_CERT:-yes}
      
      # 外部数据库配置
      - EXTERNAL_DB_DRIVER=${EXTERNAL_DB_DRIVER:-ODBC Driver 18 for SQL Server}
      - EXTERNAL_DB_SERVER=${EXTERNAL_DB_SERVER:-localhost}
      - EXTERNAL_DB_DATABASE=${EXTERNAL_DB_DATABASE:-external_db}
      - EXTERNAL_DB_UID=${EXTERNAL_DB_UID:-sa}
      - EXTERNAL_DB_PWD=${EXTERNAL_DB_PWD}
      - EXTERNAL_DB_ENCRYPT=${EXTERNAL_DB_ENCRYPT:-yes}
      - EXTERNAL_DB_TRUST_CERT=${EXTERNAL_DB_TRUST_CERT:-yes}
      
      # 应用配置
      - MAX_CONTENT_LENGTH=${MAX_CONTENT_LENGTH:-16777216}  # 16MB
      - UPLOAD_FOLDER=/app/uploads
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      
    volumes:
      # 生产环境：仅挂载数据目录，不挂载源代码
      - ./uploads:/app/uploads
      - ./logs:/app/logs
      - ./config:/app/config:ro

    
    # 健康检查
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/system/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # 资源限制 - 生产环境严格控制
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'
      # 重启策略
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  # 可选：Nginx反向代理 - 生产环境推荐
  nginx:
    image: nginx:alpine
    container_name: household-nginx-prod
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./nginx_conf:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - household-data-app
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.2'

# 网络配置
networks:
  household-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
